name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

  release:
    runs-on: ubuntu-latest
    needs: please
    if: ${{ needs.please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: lts
          cache: pnpm
      - run: pnpm instal

      - name: Build Visual Studio Code Extension
        id: build-vsce
        run: pnpm build

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pnpm: true
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          extensionFile: ${{ steps.build.outputs.vsixPath }}
          registryUrl: https://marketplace.visualstudio.com

      - name: Publish to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ needs.please.outputs.tag_name }} moonic-*.vsix
